### ISSUE TITLE
Files: Review http status codes for errors

### ISSUE THREAD

**Issue by scblack321** [tapis-project/tapis-files#102]
Check that we return sensible http status codes for various errors, such as file not found (404), perm denied (403) no credentials (401).
Basically confirm we are not getting 500 for various errors. Full review probably not feasible. Maybe do some spot checks.

**Comment by scblack321** [comment]
Did some checking, some ok (such as file not found when listing).
Did find one that is returning 500 (mkdir dir when path is an existing file).

> {
>     "result": null,
>     "status": "Internal Server Error",
>     "message": "FILES_OPSC_ERR Operations error. Tenant: dev ApiUserId: testuser2 OboTenant: dev OboUser: testuser2 Operation: mkdir System: tapisv3-exec2 Path: /test.out Error: FILES_OPSC_ERR Operations error. OboTenant: dev OboUser: testuser2 Operation: mkdirWithClient System: tapisv3-exec2 Path: /test.out Error: FILES_CLIENT_SSH_MKDIR_FILE Operation failed. Path exists as a file. OboTenant: dev OboUser: testuser2 System: tapisv3-exec2 EffectiveUser: testuser2 Host: 129.114.35.53 MkdirPath: /home/testuser2/test.out RequestPath: /home/testuser2/test.out",
>     "version": "1.3.6",
>     "commit": "ad269a23",
>     "build": "2023-05-30T21:15:51Z\n",
>     "metadata": null
> }

**Comment by dvernon-tacc** [comment]
One instance of this in the irods delete if the file doesn't exist:

dvernon@dvernon-Precision-5570:~/source/tapis/tapis-files-new$ http DELETE http://localhost:8080/v3/files/ops/tapisv3-storage4-dvernon/thing.txt $AUTH 
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 261
Content-Type: application/json

{
    "build": "2023-06-07T22:28:44Z\n",
    "commit": "unknown",
    "message": "org.irods.jargon.core.exception.FileNotFoundException: unable to find file under path",
    "metadata": null,
    "result": null,
    "status": "Internal Server Error",
    "version": "1.3.6"
}

**Comment by dvernon-tacc** [comment]
At present, this doesn't appear to be a 'generic' problem.  It seems specific to the dataclient for each operation.  The files API/Service classes rely on the exceptions that are thrown by the clients (e.g. ssh, irods, etc).  The two mentioned here are easy fixes.  I have a local fix for them at the moment.  I'll do a little more testing, and update this comment if I find more.  After that, I think we may just have to fix them as we see them come up.  I don't really know of a good way to just analyze the code and find them.

**Comment by dvernon-tacc** [comment]
In the end I found the following cases:

 linux - upload file to a path which is already a directory
 irods - upload file to a path which is already a directory
 linux - mkdir when path is existing file
 irods - mkdir when path is existing file (wasn't even returning an error)
 irods - delete file that doesn't exist

It's entirely possible that there are more.  If we do find more, we can add issues for the specific cases.  It could be in some generic code, or in some remote data client specific code (i.e. just for irods, ssh, s3, etc).
