### ISSUE TITLE
Allow users to specify recursion depth wanted in listFiles endpoint.

### ISSUE THREAD

**Issue by NotChristianGarcia** [tapis-project/tapis-files#106]
Current it looks like setting `recurse=True` in the files list endpoint sets the recursion depth to a maximum of 20. It would be useful for my case if the user could set the recursion depth wanted. For example I want to set recursion depth to 3 levels as everything after that is superfluous in my case.

**Comment by dvernon-tacc** [comment]
This is no longer needed.  I spoke with christian about it.  If it should become necessary in the future, we can reopen this and add it.
