### ISSUE TITLE
listFiles not acting as expected with recurse equal to true and the default max depth being 20.

### ISSUE THREAD

**Issue by NotChristianGarcia** [tapis-project/tapis-files#107]
Ran into personally unexpected behavior when using the listFiles `recurse=True` flag. If a directory contains more than 20 folders, only the first 20 get recursively listed. The rest are left out.

A minimal reproducible setup can be created with the following CLI commands.
```
# Create 30 folders at the same depth, all with a folder named test within.
for i in {1..30}; do mkdir dir$i && mkdir dir$i/test; done

# for good measure add another layer to dir1 to see if that affects anything (it doesn't)
mkdir dir1/test/test2
```

And this is an example of me running the listFiles and a pretty output to showcase what's happening. In this case, all `dir` folders contain a `test` inner folder, only the first 20 inner directories are returned properly. This seems like it could be caused by the recurse logic. I expect that a depth of 20 means 20 folders deep no matter the number of folders around, this could be intended, looking for clarification.

To note, adding more depth in the test folders doesn't change anything, the 20 folder limit seems to be per depth "level".
```
ls_files = t.files.listFiles(systemId = "pods_nfs_server", path = "/", recurse = True, limit = 1000)

# parsing for viewing pleasure
file_tree = {}
for file in ls_files:
    add_path(file_tree, file.path, file)

# returns
{'TESTING': {'dir1': {'test': {'test2': {}}},
             'dir10': {'test': {}},
             'dir11': {'test': {}},
             'dir12': {'test': {}},
             'dir13': {'test': {}},
             'dir14': {'test': {}},
             'dir15': {'test': {}},
             'dir16': {'test': {}},
             'dir17': {'test': {}},
             'dir18': {'test': {}},
             'dir19': {'test': {}},
             'dir2': {'test': {}},
             'dir20': {'test': {}},
             'dir21': {'test': {}},
             'dir22': {'test': {}},
             'dir23': {'test': {}},
             'dir24': {'test': {}},
             'dir25': {'test': {}},
             'dir26': {'test': {}},
             'dir27': {'test': {}},
             'dir28': {},
             'dir29': {},
             'dir3': {},
             'dir30': {},
             'dir4': {},
             'dir5': {},
             'dir6': {},
             'dir7': {},
             'dir8': {},
             'dir9': {}}}
```

**Comment by dvernon-tacc** [comment]
Also from Christian:
I noticed that limit on that endpoint defaults to 1000. It also maxes out at 1000 though with listFiles.arg2: must be less than or equal to 1000 for limit=1001. No issue for that, but I just want to confirm that's intended.

**Comment by dvernon-tacc** [comment]
For the comment about the limit of 1000 files ... That is intended.  There is code that specifically maxes out at 1000.  I'm assuming it is to prevent performance issues.  If it's a problem, we could test with a larger limit though, just let me know.  I should also mention that I wasn't here when the decisions were made, so I'm not sure how we arrived at that specific number, but again just let me know if it's an issue and we can explore bumping that up.
