### ISSUE TITLE
Files: File Transfer Failed when destinationURI is a directory

### ISSUE THREAD

**Issue by nathandf** [tapis-project/tapis-files#133]
Transfer task request body:
`{
    "tag": "globus-to-same-gloubs-test",
    "elements": [
        {
          "sourceURI": "tapis://etl-workflows-test-globus-local-outbox/data1.txt",
          "destinationURI": "tapis://etl-workflows-test-globus-remote-inbox/workdir"
        }
    ]
}`

**Comment by scblack321** [comment]
Updated title. Not globus specific. Reproduced with non-globus systems.
Files should create the file in the destination directory using the file name extracted from sourceURI.

**Comment by dvernon-tacc** [comment]
This is as designed.  There's really no way to determine if the path should be a file or a directory in this case.  You can transfer file->file or directory->directory.  The type of the destination must match the type of the file.
