### ISSUE TITLE
Files: Support wildcard search when listing files.

### ISSUE THREAD

**Issue by scblack321** [tapis-project/tapis-files#135]
Request from WMA.  Consider whether the full search facility as used in Systems, Apps, Jobs, etc. can be also be implemented in Files for listings, postits, permissions, etc.  An incremental rollout starting with file listings might be most practical.

**Comment by dvernon-tacc** [comment]
Adding a regex pattern to the request as a query parameter.  All files returned will be evaluated by applying the regex to the filename (just the bare filename, not paths).   If this is a recursive search, all files anywhere in the tree requested that match the regex will be returned.  The new query parameter will be called "regex" this will make it clear that this is a unix style regular expression, as opposed to a normal "glob" pattern.  For Example, to list files that start with the string "scienceStuff", you would use a regular expression  of "scienceStuff.*"  This matches things like "scienceStuffILike.txt" and "scienceStuff.pdf".  

Spoke with Chandra who originally raised this concern.  This will solve the issue he was facing.  Here is the original slack comment:

In tapis api, is there a mechanism to do wild card search on a file ? For example, in [listfiles](https://tapis-project.github.io/live-docs/?service=Files#tag/File-Operations/operation/listFiles), I tried to provide a wildcard for path and it did not understand the wild card. Is there another api that allows wildcard search of a file?
The background for this question: When trying to create a file, and if a file with same name already exists, we use a numeric value to suffix the name and then create it. Doing a wildcard or search on the filename allows to find the best next file name for a duplicate file name.  Reference jira task in Portal: [WP-67](https://tacc-main.atlassian.net/browse/WP-67)
