### ISSUE TITLE
Files: During transfer operation detect identical source and destination.

### ISSUE THREAD

**Issue by scblack321** [tapis-project/tapis-files#50]
During file transfers detect when source and destination are the same host+absolutePath.
For this case we should log a message and and make it a no-op.
If source and destination systemId+path match then we know they are the same.
If systemId is different we need to check for matching hosts and matching absolute paths.

**Comment by dvernon-tacc** [comment]
Does this already work this way?  Need to check to see if there is anything to be done here.
