### ISSUE TITLE
Files: Support S3 for archiveSystem in job run

### ISSUE THREAD

**Issue by scblack321** [tapis-project/tapis-files#54]
Need also to review Systems, Apps and Jobs to determine what changes are needed there.
Files may already support this as long as it iterates through all files and creates an S3 key for each entry.
Requested by Georgia S at UT Dallas.

**Comment by dvernon-tacc** [comment]
This may already work, but needs to be tested.

**Comment by dvernon-tacc** [comment]
The issue here was that jobs was trying to make a directory.  S3 does not support making directories.  Jobs has now been enhance to not try and make directories for S3.  The fulll path is in the "filename" (or key) anyway.
