### ISSUE TITLE
Files: Copying a directory to another directory silently fails for LINUX

### ISSUE THREAD

**Issue by scblack321** [tapis-project/tapis-files#80]
Copying a directory to another directory silently fails for LINUX type systems. Returns success with no errors in log.

(see comment.  moved to a separate issue) -> Moving a directory to another existing directory fails for IRODS type systems.  Returns error "Destination already exists."

**Comment by dvernon-tacc** [comment]
The Linux/copy part of this issue is fixed now.  I opened a new issue for the irods part - https://github.com/tapis-project/tapis-files/issues/85
