### ISSUE TITLE
Files: Clear permissions cache when permissions updated

### ISSUE THREAD

**Issue by scblack321** [tapis-project/tapis-files#81]
Reported by Jake Rosenberg at TACC

> I think I’m running into a caching issue with [getPermissions](https://tapis-project.github.io/live-docs/?service=Files#tag/Permissions/operation/getPermissions) . For a minute or so after I update a user’s permissions on a path, the getPermissions call returns the old permissions. This is causing issues in the UI, since we rely on file permissions to show whether a user is a reader/writer on a system.
> 
> In general it would be helpful to have a guarantee that any PUT/POST/PATCH will invalidate the cache for future GETs.

**Comment by dvernon-tacc** [comment]
I made a change so that we will invalidate the cache for a tenant/system/user anytime you make changes to the permissions.  It should help with this issue.  There is one other case - where we delete a path.  We will now invalidate select cache entries there as well.
